server:
  port: 1234

spring:
  datasource:
    #    url: jdbc:h2:~/db;MODE=MySQL;
    url: jdbc:h2:mem:db;MODE=MySQL;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: false
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
#  sql:
#    init:
#      mode: always
#      data-locations: classpath:data.sql

logging:
  pattern:
    console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  level:
    org:
      hibernate:
        type.descriptor.sql: trace
        SQL: debug

REST_API_KEY: ENC(F+HGLIZqDQqzIu7GvVA0dqRQzgZnOqvCCSFNy10VMzWg1ZqKHwayn6Oc8lNQw6XE)